Update workflows

diff --git a/.github/workflows/validate-dependencies.yml b/.github/workflows/validate-dependencies.yml
--- a/.github/workflows/validate-dependencies.yml
+++ b/.github/workflows/validate-dependencies.yml
@@ -12,7 +12,7 @@ jobs:
   check-files:
     runs-on: ubuntu-latest
     outputs:
-      has-relevant-changes: ${{ steps.changes.outputs.csprojects }}
+      has-relevant-changes: ${{ steps.changes.outputs.changes != '[]' }}
     permissions:
       pull-requests: read
     steps:
@@ -20,6 +20,8 @@ jobs:
         id: changes
         with:
           filters: |
+            workflow:
+              - '.github/workflows/validate-dependencies.yml'
             csprojects:
               - '*.csproj'
               - '**/*.csproj'
@@ -39,3 +41,22 @@ jobs:
           cache-dependency-path: '*/*.csproj'
       - working-directory: server
         run: dotnet restore
+
+  validate-dependencies-result:
+    runs-on: ubuntu-latest
+    needs:
+      - check-files
+      - validate-dependencies
+    if: ${{ always() }}
+    permissions: {}
+    steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        env:
+          DEPENDENCIES: ${{ toJson(needs) }}
+        run: |
+          FAILED_JOBS="$(echo "${DEPENDENCIES}" | jq --raw-output '
+            to_entries[]
+            | select(.value.result == "failure" or .value.result == "cancelled")
+            | .key')"
+          echo "::error title=Failed Jobs::The following jobs failed:\n${FAILED_JOBS}"
+          exit 1
